// Rebuild source-backed national XIs from committed, dated source snapshots.
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { NATIONS, selectLineup } from '../src/data/teams.js';
import { loadFootballData, pickFootballSquad, playerTuple } from './lib/football-data.mjs';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const source = process.argv[2] || path.join(root, 'scripts/data/ea-fc26.csv');
const fmSource = process.argv[3] || path.join(root, 'scripts/data/fm26-players.json');
const data = await loadFootballData(source, fmSource);
const nameToId = Object.fromEntries(Object.entries(NATIONS).map(([id, rec]) => [rec[0], id]));
const pools = {};
for (const player of data.players) {
  const id = nameToId[player.nation];
  if (!id) continue;
  (pools[id] ||= []).push(player);
}

const rosters = {}, coverage = [];
for (const [id, rec] of Object.entries(NATIONS)) {
  const pool = pools[id] || [];
  const squad = pickFootballSquad(pool);
  const lineup = selectLineup({ sport: 'football', squad });
  rosters[id] = [Math.round(lineup.rating), pool.length, squad.map(playerTuple)];
  coverage.push({ id, name: rec[0], players: squad.length,
    ea: squad.filter(p => p.sourceInfo.source === 'ea-fc').length,
    fm: squad.filter(p => p.sourceInfo.source === 'football-manager').length,
    goalkeeper: squad.some(p => p.positions.includes('GK')),
    naturalLineup: lineup.slots.every(slot => slot.player && !slot.outOfPosition) });
}

const header = `// GENERATED by npm run build-rosters from the committed EA FC / FM snapshots.
// Each entry is [effective XI strength, source pool size, player tuples].
// Tuples: [display name, primary role, game rating, source metadata].
// EA overalls are unchanged. FM source CA (1–100) is scaled once to 1–99;
// its original value, scale, database version and source URL are retained.
// No invented players or confederation-based player ratings.
`;
const body = Object.entries(rosters).map(([id, roster]) => `  '${id}': ${JSON.stringify(roster)}, // ${NATIONS[id][0]}`).join('\n');
await writeFile(path.join(root, 'src/data/rosters.js'), `${header}\nexport const ROSTERS = {\n${body}\n};\n`);
const eaSnapshots = [...new Map(data.ea.players.map(player => {
  const { edition, update, snapshotDate } = player.sourceInfo;
  return [`${edition}:${update}:${snapshotDate}`, { edition, update, snapshotDate }];
})).values()];
const report = { ea: { snapshots: eaSnapshots,
  records: data.ea.rows, excludedFictional: data.ea.fictional }, fm: data.fm,
  fmRecords: data.fmCount, omittedPossibleDuplicates: data.duplicateCandidates,
  unknownAbility: data.unknownAbility, conversion: 'round(EFEM currentAbility * 99 / 100)',
  nationalTeams: coverage.length, fullXIs: coverage.filter(r => r.players === 11).length,
  eaShirts: coverage.reduce((total, row) => total + row.ea, 0),
  fmShirts: coverage.reduce((total, row) => total + row.fm, 0), generatedShirts: 0,
  coverage };
await writeFile(path.join(root, 'docs/design/football-roster-audit.json'), `${JSON.stringify(report, null, 2)}\n`);
console.log(`National squads: ${report.fullXIs}/${report.nationalTeams} complete XIs; ${report.eaShirts} EA + ${report.fmShirts} FM players; zero generated.`);
console.log(`Excluded ${data.ea.fictional} fictional EA Brazilian domestic players; omitted ${data.duplicateCandidates} possible duplicate FM identities.`);
const incomplete = coverage.filter(row => row.players < 11 || !row.goalkeeper || !row.naturalLineup);
if (incomplete.length) console.log('Coverage requiring attention:', incomplete);
